In [ ]:
!pip install better_profanity

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting better_profanity
  Downloading better_profanity-0.7.0-py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 4.0 MB/s
Installing collected packages: better-profanity
Successfully installed better-profanity-0.7.0

In [ ]:
import pandas as pd
import numpy as np
from better_profanity import profanity

In [ ]:
df = pd.read_csv('/content/dataset.csv')

In [ ]:
df

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [ ]:
df1 = df.drop(['count', 'hate_speech', 'offensive_language', 'neither', 'class'], axis = 1)

In [ ]:
print(df1)

       Unnamed: 0                                              tweet
0               0  !!! RT @mayasolovely: As a woman you shouldn't...
1               1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2               2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3               3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4               4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...           ...                                                ...
24778       25291  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779       25292  you've gone and broke the wrong heart baby, an...
24780       25294  young buck wanna eat!!.. dat nigguh like I ain...
24781       25295              youu got wild bitches tellin you lies
24782       25296  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[24783 rows x 2 columns]

In [ ]:
df1 = df1.iloc[:, 1:]

In [ ]:
df1

                                                   tweet
0      !!! RT @mayasolovely: As a woman you shouldn't...
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...                                                  ...
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779  you've gone and broke the wrong heart baby, an...
24780  young buck wanna eat!!.. dat nigguh like I ain...
24781              youu got wild bitches tellin you lies
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[24783 rows x 1 columns]

In [ ]:
np.savetxt("test_file.txt", df1, fmt = "%s")

In [ ]:
titles = []

with open("/content/test_file.txt", "rt", encoding = "utf-8") as f:
    lines = f.readlines()
    for x in lines:
        line = x.strip("\n")
        titles.append(line)

In [ ]:
cuss_words = []

for x in titles:
    c = 0
    for i in x.split():
        value = profanity.contains_profanity(i)
        if value == True:
            c += 1
    cuss_words.append(c)

In [ ]:
data = {"Sentences":titles,
        "Curse Words":cuss_words}

df2 = pd.DataFrame(data)

In [ ]:
df2

                                               Sentences  Curse Words
0      !!! RT @mayasolovely: As a woman you shouldn't...            0
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...            0
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...            3
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...            0
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...            2
...                                                  ...          ...
26948  you's a muthaf***in lie &#8220;@LifeAsKing: @2...            0
26949  you've gone and broke the wrong heart baby, an...            0
26950  young buck wanna eat!!.. dat nigguh like I ain...            1
26951              youu got wild bitches tellin you lies            1
26952  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...            0

[26953 rows x 2 columns]

In [ ]:
# df2.to_excel("Profanity_Check.xls", header = True)